[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
import = { path="libs/import/"}
regex = "1.7.0"
pathfinding = "4.1.1"
